name: WakaTime Status Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# AÑADE ESTO: Le da permiso al bot para modificar el README
permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          TIME_RANGE: last_7_days
